# Generated by Django 2.2.5 on 2019-09-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=20)),
                ('depart', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('exp', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
