# Generated by Django 2.2.5 on 2019-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sreg1',
            fields=[
                ('sname', models.CharField(max_length=10)),
                ('sbranch', models.CharField(max_length=10)),
                ('syear', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
