# Generated by Django 2.2.5 on 2019-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_sreg1'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('eee', 'eee'), ('ece', 'ece'), ('cse', 'cse'), ('mech', 'mech'), ('civil', 'civil')], max_length=30)),
                ('exam', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
