# Generated by Django 2.2.5 on 2019-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_auto_20190924_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('eee', 'eee'), ('ece', 'ece'), ('cse', 'cse'), ('mech', 'mech'), ('civil', 'civil')], max_length=30)),
                ('sports', models.CharField(choices=[('cricket', 'cricket'), ('football', 'football'), ('vollyball', 'vollyball'), ('kabadi', 'kabadi'), ('tennis', 'tennis')], max_length=30)),
                ('year', models.IntegerField()),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
