# Generated by Django 2.2.5 on 2019-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_events_cultural'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('eee', 'eee'), ('ece', 'ece'), ('cse', 'cse'), ('mech', 'mech'), ('civil', 'civil')], max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('subjects', models.CharField(choices=[('maths', 'maths'), ('physics', 'physics'), ('communication', 'communication'), ('edc', 'edc'), ('electricalmotors', 'electricalmotors')], max_length=30)),
                ('year', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
