# Generated by Django 2.2.5 on 2019-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('eee', 'eee'), ('ece', 'ece'), ('cse', 'cse'), ('mech', 'mech'), ('civil', 'civil')], max_length=30)),
                ('flor', models.IntegerField()),
                ('blockno', models.IntegerField()),
            ],
        ),
    ]
