# Generated by Django 2.2.5 on 2019-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
