# Generated by Django 2.2.5 on 2019-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_departments_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('departments', models.CharField(choices=[('eee', 'eee'), ('ece', 'ece'), ('cse', 'cse'), ('mech', 'mech'), ('civil', 'civil')], max_length=30)),
                ('year', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
            ],
        ),
    ]
